### ISSUE TITLE
Use this for a better terminal video making experience

### ISSUE THREAD

**Issue by d3287t328** [unconv/gpt-autopilot#10]
https://github.com/faressoft/terminalizer

The quality of the current one leaves much to be desired.

**Comment by unconv** [comment]
Thanks! Yeah, stuffing a 12 minute video in a 10 megabyte file was a mistake lol

**Comment by unconv** [comment]
Created better demo videos. Terminalizer might not work here as I need to record the actual application in the browser too.

### GPT-4

https://github.com/unconv/gpt-autopilot/assets/120440395/78f0fb79-7f40-4aee-b6df-f9bea1457b5f

### GPT-3.5

https://github.com/unconv/gpt-autopilot/assets/120440395/34c814e9-9360-4c08-b776-98366ccc37b7
