### ISSUE TITLE
There is no .exe file in Windows standalone version 0.4.0

### ISSUE THREAD

**Issue by OzMaatuk** [unconv/gpt-autopilot#17]
the .exe is missing for version 0.4.0 windows standalone

**Comment by unconv** [comment]
What's that?

![Screenshot from 2023-07-09 04-06-49](https://github.com/unconv/gpt-autopilot/assets/120440395/7889c98d-b159-4ab1-b1e8-524a522578f3)

**Comment by OzMaatuk** [comment]
So Norton Antivirus recognizes it as malicious

**Comment by unconv** [comment]
@OzMaatuk well, it's an AI with access to the filesystem and terminal, so... haha

**Comment by OzMaatuk** [comment]
Yep, think will try to use the source instead.
Thanks, Issue is closed.
